<?php
namespace Authwave\Security;

enum Action {
	case LOGIN_REQUESTED;
	case LOGOUT_REQUESTED;
	case CLIENT_LOGIN_REDIRECTED;
	case EMAIL_SUBMITTED;
	case EMAIL_REJECTED;
	case LOGIN_CANCELLED;
	case PASSWORD_LOGIN_SUCCEEDED;
	case PASSWORD_LOGIN_FAILED;
	case SECURITY_CODE_REQUESTED;
	case EMAIL_SCHEDULED;
	case USER_CREATED;
	case SECURITY_CODE_ACCEPTED;
	case SECURITY_CODE_REJECTED;
	case LOGIN_COMPLETED;
}
